version: "3"

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 35432:5432
    # volumes:
      # - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

# volumes:
#   postgres_data:
#     driver: local